## Checking employment trends in R

In [24]:
update_proportions_and_regressions = FALSE # Set to True to update your
# proportion and regression calculations; set to False to load .csv copies
# of these files instead (thus dramatically reducing the time needed 
# to run the program)

# Importing relevant datasets:
# (I installed all of these via Conda, since I was having trouble with
# alternative installation methods on Linux.)
# based on
# https://tidy-survey-r.github.io/tidy-survey-book/c05-descriptive-analysis.html
library(tidyverse)
library(broom)
library(survey)
library(srvyr)

In [25]:
df <- read_csv('/home/kjb3/D1V1/kjb3largefiles/large_programming/datasets/cps/cps_employment_trends_revised.csv',
col_types = list(year_as_str = col_character())) %>% select(!age) # The
# age field is actually string-based, so I'm removing it in order to prevent
# it from getting confused with the 'age_as_int' field.

Checking the number of rows in the DataFrame:
(See https://dplyr.tidyverse.org/reference/n_distinct.html?q=nrow#null)

In [26]:
nrow(df)

[1] 23488604

In [27]:
# df %>% glimpse()

The following cell provides as somewhat 'hacky' way to specify 2026 as the baseline for an upcoming logistic regression. (It does so by making it the first year when its field is sorted in alphabetical order.)

(See https://dplyr.tidyverse.org/articles/recoding-replacing.html)

In [28]:
df <- df %>% mutate(
year_as_str_last_year_first = year_as_str %>% replace_when(
year_as_str == '2026' ~ '0_2026'))

Creating a survey design object:

(See https://tidy-survey-r.github.io/tidy-survey-book/c10-sample-designs-replicate-weights.html)

In [29]:
sd_df <- df %>% as_survey_design(weights = year_wtfinl, 
strata = final_stratum_revision, ids = cpsid, nest = TRUE)

Creating an object just for 2025 data in order to speed up processing times:

(Since the original CPS data was at the monthly level, I don't think that filtering out years at this stage would distort our results as would, say, filtering the dataset to include *only* software developers.) (See https://tidy-survey-r.github.io/tidy-survey-book/c04-getting-started.html#c04-getting-started for an explanation of why you shouldn't prematurely filter variables out of your sample for a given period.)

In [30]:
df_25 <- df %>% filter(year == 2025)
sd_df_25 <- df_25 %>% as_survey_design(weights = year_wtfinl, 
strata = final_stratum_revision, ids = cpsid, nest = TRUE)
# sd_df_25

In [31]:
nrow(df_25)

[1] 1041831

Creating an object just for 2022 through 2026 (which will prove useful for logistic regressions):

In [32]:
df_22_26 <- df %>% filter(year %in% c(2022, 2023, 2024, 2025, 2026))
sd_df_22_26 <- df_22_26 %>% as_survey_design(weights = year_wtfinl, 
strata = final_stratum_revision, ids = cpsid, nest = TRUE)
# sd_df_22_26

In [33]:
nrow(df_22_26)

[1] 5379704

In [36]:
sd_df_22_26_ages_22_65_only <- sd_df_22_26 %>% filter(age_as_int >= 22 & age_as_int <= 65)

In [37]:
sd_df_ages_22_65_only <- sd_df %>% filter(age_as_int >= 22 & age_as_int <= 65)

## Data checks

### 1. Software-developer employment totals by year

In [34]:
sd_df_25_employed_devs_only <- sd_df_25 %>% filter(
occ2010 == 'Software developers, applications and systems software' & employed == 1)

The following code is based on https://tidy-survey-r.github.io/tidy-survey-book/c05-descriptive-analysis.html .

In [35]:
csv_path = 'R_Datasets/dev_emp_2025.csv'
if (update_proportions_and_regressions == TRUE)
    {df_dev_emp_2025 = sd_df_25_employed_devs_only %>% survey_count(
year, vartype = c("se", "ci", "var", "cv"))

write_csv(df_dev_emp_2025, csv_path)
     }

df_dev_emp_2025 = read_csv(csv_path)
df_dev_emp_2025

Rows: 1 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (7): year, n, n_se, n_low, n_upp, n_var, n_cv

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  year n       n_se     n_low   n_upp   n_var      n_cv
1 2025 2331220 60146.87 2213263 2449176 3617646432 0.0258006

These standard-error, confidence-itnerval, and CV values match those that I got in svy. (See 'Employment totals by year' section in employment_data_analyses.ipynb.)

### 2. Logistic regression that evaluates whether the proportion of individuals ages 22-65 who are employed as developers has increased significantly from previous years to the current year:

The following logistic-regression code is based on: https://tidy-survey-r.github.io/tidy-survey-book/c07-modeling.html

For a comparison of svy and R's logistic-regression approaches, see: https://svylab.com/learn/notes/posts/svy-vs-r-comparison/index.html

In [39]:
csv_path = 'R_Datasets/dev_emp_prop_by_year_reg_results_full.csv'
if (update_proportions_and_regressions == TRUE)
{
dev_emp_prop_by_year_reg_results_full <- sd_df_ages_22_65_only  %>% svyglm(
formula = employed_as_software_developer ~ year_as_str_last_year_first,
design = ., na.action = na.omit, family = quasibinomial)


df_dev_emp_prop_by_year_reg_results_full = tidy(dev_emp_prop_by_year_reg_results_full)

write_csv(df_dev_emp_prop_by_year_reg_results_full, csv_path)
}
    
df_dev_emp_prop_by_year_reg_results_full = read_csv(csv_path)

df_dev_emp_prop_by_year_reg_results_full

Warning message in summary.glm(g):
“observations with zero weight not used for calculating dispersion”
Warning message in summary.glm(glm.object):
“observations with zero weight not used for calculating dispersion”
Rows: 17 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): term
dbl (4): estimate, std.error, statistic, p.value

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

   term                            estimate   std.error  statistic
1  (Intercept)                     -4.3047927 0.03084185 -139.576322
2  year_as_str_last_year_first2010 -0.8534725 0.04350734  -19.616750
3  year_as_str_last_year_first2011 -0.8359462 0.04294253  -19.466627
4  year_as_str_last_year_first2012 -0.8169627 0.04267879  -19.142125
5  year_as_str_last_year_first2013 -0.8118683 0.04225295  -19.214477
6  year_as_str_last_year_first2014 -0.7078642 0.04216944  -16.786189
7  year_as_str_last_year_first2015 -0.6168011 0.04168514  -14.796664
8  year_as_str_last_year_first2016 -0.5381413 0.04090433  -13.156097
9  year_as_str_last_year_first2017 -0.5011486 0.04071627  -12.308314
10 year_as_str_last_year_first2018 -0.4152714 0.04051265  -10.250414
11 year_as_str_last_year_first2019 -0.3413211 0.04036385   -8.456109
12 year_as_str_last_year_first2020 -0.2514955 0.04076153   -6.169923
13 year_as_str_last_year_first2021 -0.2307673 0.04040111   -5.711904
14 year_as_str_last_year_first2022 -0.1597263 0.04026315   -3.967060
15 year_as_str_last_year_first2023 -0.1541254 0.04027489   -3.826835
16 year_as_str_last_year_first2024 -0.1719728 0.04012379   -4.286056
17 year_as_str_last_year_first2025 -0.1054487 0.03429610   -3.074655
   p.value
1  0.000000e+00
2  1.142413e-85
3  2.162060e-84
4  1.153328e-81
5  2.869872e-82
6  3.124321e-63
7  1.552663e-49
8  1.578410e-39
9  8.205316e-35
10 1.180755e-24
11 2.767075e-17
12 6.834203e-10
13 1.117417e-08
14 7.276836e-05
15 1.298071e-04
16 1.818857e-05
17 2.107500e-03

Not sure why the following tidy() calls are taking so long:

The p-values within this output (at least for 2022 onward, which were the only ones I checked) match those within employment_trends.ipynb.

## 2. Calculating the proportion of individuals aged 22-65, by year, employed as software developers from 2022 onward

(The following code is based on https://tidy-survey-r.github.io/tidy-survey-book/c05-descriptive-analysis.html#desc-meanprop)

Since `employed_as_software_developer` is a boolean field (with no -1 values), I probably could have used `survey_mean()` here instead.

In [38]:
csv_path = 'R_Datasets/dev_employment_proportion_by_year.csv'
if (update_proportions_and_regressions == TRUE)
    {
df_dev_employment_proportion_by_year <- sd_df_22_26_ages_22_65_only %>% group_by(
year_as_str, employed_as_software_developer) %>% summarize(
p = survey_prop(vartype = c("se", "ci", "var", "cv")))
write_csv(df_dev_employment_proportion_by_year, csv_path)
}

df_dev_employment_proportion_by_year = read_csv(csv_path)
df_dev_employment_proportion_by_year

When `proportion` is unspecified, `survey_prop()` now defaults to `proportion = TRUE`.
ℹ This should improve confidence interval coverage.
This message is displayed once per session.
Warning message:
“There were 20 warnings in `dplyr::summarise()`.
The first warning was:
ℹ In argument: `p = survey_prop(vartype = c("se", "ci", "var", "cv"))`.
ℹ In group 1: `year_as_str = "2022"`, `employed_as_software_developer = 0`.
Caused by warning in `summary.glm()`:
! observations with zero weight not used for calculating dispersion
ℹ Run `dplyr::last_dplyr_warnings()` to see the 19 remaining warnings.”
Rows: 10 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (8): year_as_str, employed_as_software_developer, p, p_se, p_low, p_upp,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

   year_as_str employed_as_software_developer p          p_se
1  2022        0                              0.98862075 0.0002899929
2  2022        1                              0.01137925 0.0002899929
3  2023        0                              0.98855756 0.0002919277
4  2023        1                              0.01144244 0.0002919277
5  2024        0                              0.98875770 0.0002895627
6  2024        1                              0.01124230 0.0002895627
7  2025        0                              0.98799366 0.0003149996
8  2025        1                              0.01200634 0.0003149996
9  2026        0                              0.98667623 0.0004048551
10 2026        1                              0.01332377 0.0004048551
   p_low      p_upp      p_var        p_cv
1  0.98803811 0.98917532 8.409591e-08 0.0002933308
2  0.01082468 0.01196189 8.409591e-08 0.0254843566
3  0.98797102 0.98911582 8.522180e-08 0.0002953068
4  0.01088418 0.01202898 8.522180e-08 0.0255127264
5  0.98817577 0.98931130 8.384658e-08 0.0002928551
6  0.01068870 0.01182423 8.384658e-08 0.0257565300
7  0.98736033 0.98859562 9.922472e-08 0.0003188275
8  0.01140438 0.01263967 9.922472e-08 0.0262360996
9  0.98585897 0.98744687 1.639077e-07 0.0004103222
10 0.01255313 0.01414103 1.639077e-07 0.0303859401

The 2025 and 2026 proportions match those in employment_trends.ipynb.

## 2. Calculating the proportion of individuals, by age range, employed as software developers from 2022 onward

(Since we'd like to evaluate proportions for all age ranges, we'll remove the age filter applied in the previous analysis.)

Note: When requesting a new analysis, the following cell took around 2 hours and 39 minutes to run.

In [17]:
csv_path = 'R_Datasets/dev_employment_proportion_by_year_and_age_range.csv'
if (update_proportions_and_regressions == TRUE)
    {df_dev_employment_proportion_by_year_and_age_range <- sd_df_22_26 %>% group_by(
year_as_str, age_range, employed_as_software_developer) %>% summarize(
p = survey_prop(vartype = c("se", "ci", "var", "cv")))

write_csv(df_dev_employment_proportion_by_year_and_age_range, csv_path)
}

df_dev_employment_proportion_by_year_and_age_range = read_csv(csv_path)

df_dev_employment_proportion_by_year_and_age_range

Rows: 100 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): age_range
dbl (8): year_as_str, employed_as_software_developer, p, p_se, p_low, p_upp,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    year_as_str age_range     employed_as_software_developer p
1   2022        21 or younger 0                              0.9998429215
2   2022        21 or younger 1                              0.0001570785
3   2022        22-24         0                              0.9902267844
4   2022        22-24         1                              0.0097732156
5   2022        25-29         0                              0.9827827812
6   2022        25-29         1                              0.0172172188
7   2022        30-34         0                              0.9827936377
8   2022        30-34         1                              0.0172063623
9   2022        35-39         0                              0.9848786755
10  2022        35-39         1                              0.0151213245
11  2022        40-44         0                              0.9881958832
12  2022        40-44         1                              0.0118041168
13  2022        45-49         0                              0.9895728549
14  2022        45-49         1                              0.0104271451
15  2022        50-54         0                              0.9906686246
16  2022        50-54         1                              0.0093313754
17  2022        55-59         0                              0.9937277908
18  2022        55-59         1                              0.0062722092
19  2022        60 or older   0                              0.9978765090
20  2022        60 or older   1                              0.0021234910
21  2023        21 or younger 0                              0.9997822201
22  2023        21 or younger 1                              0.0002177799
23  2023        22-24         0                              0.9912432440
24  2023        22-24         1                              0.0087567560
25  2023        25-29         0                              0.9825537211
26  2023        25-29         1                              0.0174462789
27  2023        30-34         0                              0.9817969858
28  2023        30-34         1                              0.0182030142
29  2023        35-39         0                              0.9840284953
30  2023        35-39         1                              0.0159715047
⋮   ⋮           ⋮             ⋮                              ⋮
71  2025        40-44         0                              0.9859298054
72  2025        40-44         1                              0.0140701946
73  2025        45-49         0                              0.9891248642
74  2025        45-49         1                              0.0108751358
75  2025        50-54         0                              0.9909956722
76  2025        50-54         1                              0.0090043278
77  2025        55-59         0                              0.9933678160
78  2025        55-59         1                              0.0066321840
79  2025        60 or older   0                              0.9982505643
80  2025        60 or older   1                              0.0017494357
81  2026        21 or younger 0                              0.9998234187
82  2026        21 or younger 1                              0.0001765813
83  2026        22-24         0                              0.9906418463
84  2026        22-24         1                              0.0093581537
85  2026        25-29         0                              0.9817100184
86  2026        25-29         1                              0.0182899816
87  2026        30-34         0                              0.9775405709
88  2026        30-34         1                              0.0224594291
89  2026        35-39         0                              0.9818208273
90  2026        35-39         1                              0.0181791727
91  2026        40-44         0                              0.9841028140
92  2026        40-44         1                              0.0158971860
93  2026        45-49         0                              0.9879847895
94  2026        45-49         1                              0.0120152105
95  2026        50-54         0                              0.9915504735
96  2026        50-54         1                              0.0084495265
97  2026        55-59         0                              0.9916428422
98  2026        55-59         1                              0.0083571578
99  2026        60 or older   0                              0.9979838401
100 2026        60 or older   1                              0.0020161599
    p_se         p_low        p_upp        p_var        p_cv
1   3.895382e-05 9.997446e-01 0.9999033904 1.517400e-09 3.895994e-05
2   3.895382e-05 9.660962e-05 0.0002553858 1.517400e-09 2.479894e-01
3   1.031799e-03 9.879828e-01 0.9920551343 1.064609e-06 1.041983e-03
4   1.031799e-03 7.944866e-03 0.0120172265 1.064609e-06 1.055742e-01
5   1.071860e-03 9.805511e-01 0.9847623930 1.148884e-06 1.090638e-03
6   1.071860e-03 1.523761e-02 0.0194489349 1.148884e-06 6.225513e-02
7   9.841298e-04 9.807547e-01 0.9846199477 9.685115e-07 1.001360e-03
8   9.841298e-04 1.538005e-02 0.0192452993 9.685115e-07 5.719569e-02
9   9.067456e-04 9.829947e-01 0.9865567789 8.221876e-07 9.206673e-04
10  9.067456e-04 1.344322e-02 0.0170052932 8.221876e-07 5.996470e-02
11  8.117060e-04 9.864943e-01 0.9896853218 6.588666e-07 8.214019e-04
12  8.117060e-04 1.031468e-02 0.0135056951 6.588666e-07 6.876465e-02
13  7.829435e-04 9.879211e-01 0.9910008018 6.130005e-07 7.911934e-04
14  7.829435e-04 8.999198e-03 0.0120789097 6.130005e-07 7.508704e-02
15  7.273277e-04 9.891297e-01 0.9919914524 5.290055e-07 7.341786e-04
16  7.273277e-04 8.008548e-03 0.0108703095 5.290055e-07 7.794431e-02
17  5.839624e-04 9.924730e-01 0.9947745006 3.410120e-07 5.876482e-04
18  5.839624e-04 5.225499e-03 0.0075269970 3.410120e-07 9.310314e-02
19  1.757032e-04 9.975027e-01 0.9981944559 3.087161e-08 1.760771e-04
20  1.757032e-04 1.805544e-03 0.0024972867 3.087161e-08 8.274261e-02
21  5.550111e-05 9.996411e-01 0.9998678464 3.080373e-09 5.551320e-05
22  5.550111e-05 1.321536e-04 0.0003588663 3.080373e-09 2.548495e-01
23  9.682156e-04 9.891267e-01 0.9929507398 9.374414e-07 9.767689e-04
24  9.682156e-04 7.049260e-03 0.0108733183 9.374414e-07 1.105678e-01
25  1.077734e-03 9.803109e-01 0.9845451119 1.161510e-06 1.096870e-03
26  1.077734e-03 1.545489e-02 0.0196891327 1.161510e-06 6.177441e-02
27  9.915768e-04 9.797482e-01 0.9836419634 9.832245e-07 1.009961e-03
28  9.915768e-04 1.635804e-02 0.0202517974 9.832245e-07 5.447322e-02
29  9.706320e-04 9.820103e-01 0.9858235414 9.421265e-07 9.863861e-04
30  9.706320e-04 1.417646e-02 0.0179896948 9.421265e-07 6.077274e-02
⋮   ⋮            ⋮            ⋮            ⋮            ⋮
71  9.383085e-04 9.839672e-01 0.9876551852 8.804229e-07 9.516991e-04
72  9.383085e-04 1.234481e-02 0.0160328086 8.804229e-07 6.668767e-02
73  8.386335e-04 9.873521e-01 0.9906514899 7.033062e-07 8.478540e-04
74  8.386335e-04 9.348510e-03 0.0126478789 7.033062e-07 7.711476e-02
75  7.711948e-04 9.893513e-01 0.9923880572 5.947414e-07 7.782020e-04
76  7.711948e-04 7.611943e-03 0.0106486765 5.947414e-07 8.564712e-02
77  6.221367e-04 9.920301e-01 0.9944822419 3.870541e-07 6.262904e-04
78  6.221367e-04 5.517758e-03 0.0079698876 3.870541e-07 9.380570e-02
79  1.587781e-04 9.979100e-01 0.9985356945 2.521049e-08 1.590564e-04
80  1.587781e-04 1.464305e-03 0.0020899703 2.521049e-08 9.075962e-02
81  5.483592e-05 9.996755e-01 0.9999039276 3.006978e-09 5.484561e-05
82  5.483592e-05 9.607237e-05 0.0003245351 3.006978e-09 3.105420e-01
83  1.251916e-03 9.878407e-01 0.9928023925 1.567295e-06 1.263743e-03
84  1.251916e-03 7.197608e-03 0.0121593000 1.567295e-06 1.337782e-01
85  1.417134e-03 9.787153e-01 0.9842901522 2.008268e-06 1.443536e-03
86  1.417134e-03 1.570985e-02 0.0212847047 2.008268e-06 7.748142e-02
87  1.520538e-03 9.743590e-01 0.9803353254 2.312034e-06 1.555473e-03
88  1.520538e-03 1.966467e-02 0.0256409869 2.312034e-06 6.770152e-02
89  1.264200e-03 9.791700e-01 0.9841397877 1.598202e-06 1.287608e-03
90  1.264200e-03 1.586021e-02 0.0208300176 1.598202e-06 6.954112e-02
91  1.225830e-03 9.815128e-01 0.9863350585 1.502658e-06 1.245632e-03
92  1.225830e-03 1.366494e-02 0.0184872453 1.502658e-06 7.710985e-02
93  1.025587e-03 9.857993e-01 0.9898373995 1.051829e-06 1.038060e-03
94  1.025587e-03 1.016260e-02 0.0142007004 1.051829e-06 8.535740e-02
95  9.183323e-04 9.895467e-01 0.9931728193 8.433343e-07 9.261579e-04
96  9.183323e-04 6.827181e-03 0.0104533333 8.433343e-07 1.086845e-01
97  8.482608e-04 9.898052e-01 0.9931515451 7.195464e-07 8.554096e-04
98  8.482608e-04 6.848455e-03 0.0101948137 7.195464e-07 1.015011e-01
99  1.917419e-04 9.975708e-01 0.9983267570 3.676494e-08 1.921292e-04
100 1.917419e-04 1.673243e-03 0.0024291836 3.676494e-08 9.510251e-02

### 3. Logistic regression that evaluates whether software employment *by age group* has increased significantly from previous years to the most recent year

(One option would be to loop through a list of all age ranges, then perform a logistic regression for each. However, to speed things up, I'll simply perform standalone regressions for at least some of the age ranges for which I found, in my Python-based analysis, a significant difference in employment proportions between 2022 and 2026. (I'll focus on age ranges with relatively high, though still-significant, p-values in order to check whether my significance findings in Python were correct.)

In [18]:
csv_path = 'dev_emp_prop_by_year_reg_results_35_39'
if (update_proportions_and_regressions == TRUE) {
dev_emp_prop_by_year_reg_results_35_39 <- sd_df_22_26  %>% filter (
age_range == '35-39') %>% svyglm(
formula = employed_as_software_developer ~ year_as_str_last_year_first,
design = ., na.action = na.omit, family = quasibinomial)

df_dev_emp_prop_by_year_reg_results_35_39 = tidy(dev_emp_prop_by_year_reg_results_35_39)
write_csv(df_dev_emp_prop_by_year_reg_results_35_39, csv_path)
    }

df_dev_emp_prop_by_year_reg_results_35_39 = read_csv(csv_path)
df_dev_emp_prop_by_year_reg_results_35_39

Rows: 5 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): term
dbl (4): estimate, std.error, statistic, p.value

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  term                            estimate   std.error  statistic  p.value
1 (Intercept)                     -3.9891323 0.07082872 -56.320826 0.000000000
2 year_as_str_last_year_first2022 -0.1872802 0.09342984  -2.004501 0.045020165
3 year_as_str_last_year_first2023 -0.1317164 0.09400853  -1.401112 0.161185093
4 year_as_str_last_year_first2024 -0.2715364 0.09497957  -2.858893 0.004252456
5 year_as_str_last_year_first2025 -0.1286275 0.08199279  -1.568766 0.116706977

In [19]:
csv_path = 'R_Datasets/dev_emp_prop_by_year_reg_results_55_59.csv'
if (update_proportions_and_regressions == TRUE)
    {
dev_emp_prop_by_year_reg_results_55_59 <- sd_df_22_26  %>% filter (
age_range == '55-59') %>% svyglm(
formula = employed_as_software_developer ~ year_as_str_last_year_first,
design = ., na.action = na.omit, family = quasibinomial)
df_dev_emp_prop_by_year_reg_results_55_59 = tidy(dev_emp_prop_by_year_reg_results_55_59)
write_csv(df_dev_emp_prop_by_year_reg_results_55_59, csv_path)
}
    
df_dev_emp_prop_by_year_reg_results_55_59 = read_csv(csv_path)
df_dev_emp_prop_by_year_reg_results_55_59

Rows: 5 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): term
dbl (4): estimate, std.error, statistic, p.value

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  term                            estimate   std.error statistic  p.value
1 (Intercept)                     -4.7762446 0.1023565 -46.662826 0.00000000
2 year_as_str_last_year_first2022 -0.2890900 0.1387813  -2.083061 0.03724941
3 year_as_str_last_year_first2023 -0.3066752 0.1397833  -2.193933 0.02824364
4 year_as_str_last_year_first2024 -0.2018373 0.1357339  -1.487007 0.13701753
5 year_as_str_last_year_first2025 -0.2329222 0.1192608  -1.953050 0.05081780

The 2022 p-values match those in my svy-based analyses.